backend:
   name: github
   repo: skimkoh/docusaurus-test   # replace with your GitHub repo
   branch: main                    # or master
   base_url: http://localhost:8081  # your local decap-server URL

media_folder: "static/img/uploads"   # Where uploaded images are stored
public_folder: "/img/uploads"

collections:
  - name: "docs"
    label: "Documentation"
    folder: "docs"                  # Docusaurus docs folder
    create: true
    slug: "{{slug}}"                # Filename generation
    extension: "mdx"
    format: "frontmatter"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "sidebar_label", label: "Sidebar Label", widget: "string", required: false }
      - { name: "id", label: "Doc ID", widget: "string", required: false }
      - { name: "body", label: "Content", widget: "markdown" }